language: cpp    
sudo: required
dist: trusty

before_install:
    - sudo apt-get install -y build-essential cmake libcgroup-dev

install:
    - mkdir lib

before_script:
    - cd lib

script:
    - cmake ..
    - make
