sudo: required
dist: trusty
language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
env: CMAKE_CXX_COMPILER=g++-5

before_install:
    - sudo apt-get install -y build-essential cmake libcgroup-dev

install:
    - mkdir lib

before_script:
    - cd lib

script:
    - cmake ..
    - make
